### ISSUE TITLE
RAW token proměnná má hardcodované jméno

### ISSUE THREAD

**Issue by JosefKuchar** [bakalari-api/python-token-generator#1]
Ahoj,
máš tam hardcodované jméno 050123agds, takže to nebude fungovat s jiným jménem ;)
`rawtoken = '*login*050123agds*pwd*' + hashpass + '*sgn*ANDR' + now`

**Comment by mariansam** [comment]
To je tak, když to člověk dělá pro sebe a pak to neudělám univerzální. Jinak promiň za pozdní odpověď, nepřišel mi o tý issue email. Funguje?

**Comment by JosefKuchar** [comment]
Považuji to za opravené 👍
